# Site settings
title: Hanzi Writer
email: chanindav@gmail.com
description: > #
  Hanzi Writer is a free and open-source javascript library for both animating
  simplified Chinese characters and quizzing users on character stroke order.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chanind.github.io/hanzi-writer/" # the base hostname & protocol for your site
github_username:  chanind

# Build settings
markdown: kramdown
